export interface CamConfig {
    framesize: number,
    quality: number,
    brightness:number,
    contrast:number,
    saturation:number,
    specialEffect:number,
    awb:boolean,
    awbGain:boolean,
    wbMode:number,
    aecSensor:boolean,
    aecDsp:boolean,
    aeLevel:number,
    aecValue:number,
    agc:boolean,
    agcGain:number,
    gainceiling:number,
    bpc:boolean,
    wpc:boolean,
    rawGma:boolean,
    lenc:boolean,
    hmirror:boolean,
    vflip:boolean,
    dcw:boolean,
    colorbar:boolean,
    faceDetect:boolean,
    faceRecognize:boolean,
    flashOn:boolean,
  };
